### ISSUE TITLE
Your client died

### ISSUE THREAD

**Issue by FloWi** [eseidel/space_traders#4]
Hey!

Hope I'm not bothering you. Just wanted to let you know that your client died. 

Since I can't write you on discord I thought to let you know here :) 

https://flwi-spacetraders-leaderboard-crimson-waterfall-7968.fly.dev/#/historic-leaderboard?agent=ESEIDEL&agent=FLWI&hours=168

**Comment by eseidel** [comment]
Thanks!  Yeah, I (abruptly) decided it was time to step away this weekend.  I need to use more of my nights and weekends for work at the moment and a way to do that is to clear them from non-work projects.  It was fun hacking with you all.  I left my client running (but it appears to have crashed) and left the Discord.
